# Author: José Rodolfo (jric2002)
import matplotlib.pyplot as plt
print("Datos")
print("-" * 6)
x1 = float(input("Ingresa un valor para 'x1': "))
y1 = float(input("Ingresa un valor para 'y1': "))
x2 = float(input("Ingresa un valor para 'x2': "))
y2 = float(input("Ingresa un valor para 'y2': "))
x = float(input("Ingresa un valor para 'x': "))
print()
y = (((x - x1) / (x2 - x1)) * (y2 - y1)) + y1 # Formula para hallar el valor de Y
print("x1: " + str(x1), "y1: " + str(y1), sep='\t')
print("x2: " + str(x2), "y2: " + str(y2), sep='\t')
print("Valor de 'y' es: " + str(y))
plt.grid(color="black", linestyle='--')
plt.plot([x1, x, x2], [y1, y, y2], '-', marker='o', mec='g', mfc='g', color="orange", label="Recta Aproximada") # Resultado de usar interpolación lineal
plt.xlim((2 * x1) - x, (2 * x2) - x)
plt.ylim((2 * y1) - y, (2 * y2) - y)
plt.title("Grafica 1")
plt.ylabel("Eje Y")
plt.xlabel("Eje X")
plt.suptitle("Interpolación Lineal")
plt.legend()
plt.grid(color="black", linestyle='--')
plt.show()