/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codeideryj;

import java.awt.Color;
import javax.swing.JTextPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;

/**
 *
 * @author usuario
 */
public class IDE extends javax.swing.JFrame {

    
    NumeroLinea numerolinea;
    Directorio dir;
    /**
     * Creates new form IDE
     */
    public IDE() {
        initComponents();
        inizializar();
        colors();
    }
    
//METODO PARA ENCONTRAR LAS ULTIMAS CADENAS
    private int findLastNonWordChar(String text, int index) {
        while (--index >= 0) {
            //  \\W = [A-Za-Z0-9]
            if (String.valueOf(text.charAt(index)).matches("\\W")) {
                break;
            }
        }
        return index;
    }
    
//METODO PARA ENCONTRAR LAS PRIMERAS CADENAS 
    private int findFirstNonWordChar(String text, int index) {
        while (index < text.length()) {
            if (String.valueOf(text.charAt(index)).matches("\\W")) {
                break;
            }
            index++;
        }
        return index;
    }
    
    //METODO PARA PINTAS LAS PALABRAS RESEVADAS
    private void colors() {
        final StyleContext cont = StyleContext.getDefaultStyleContext();
        final AttributeSet attred = cont.addAttribute(cont.getEmptySet(), StyleConstants.Foreground, new Color(255, 0, 35));
        final AttributeSet attgreen = cont.addAttribute(cont.getEmptySet(), StyleConstants.Foreground, new Color(0, 255, 54));
        final AttributeSet attblue = cont.addAttribute(cont.getEmptySet(), StyleConstants.Foreground, new Color(0, 147, 255));
        final AttributeSet attblack = cont.addAttribute(cont.getEmptySet(), StyleConstants.Foreground, new Color(0, 0, 0));

        DefaultStyledDocument doc = new DefaultStyledDocument(){
            public void insertString(int offset, String str, AttributeSet a) throws BadLocationException {
                super.insertString(offset, str, a);

                String text = getText(0, getLength());
                int before = findLastNonWordChar(text, offset);
                if (before < 0) {
                    before = 0;
                }
                int after = findFirstNonWordChar(text, offset + str.length());
                int wordL = before;
                int wordR = before;

                while (wordR <= after) {
                    if (wordR == after || String.valueOf(text.charAt(wordR)).matches("\\W")) {
                        if (text.substring(wordL, wordR).matches("(\\W)*(documento|fdocumento|encabezado|fencabezado|cuerpo|fcuerpo|titulo|ftitulo|css|js|e1|fe1|e2|fe2|p|fp|a|fa|img|comilla_doble|valor|entonces|loop)")) {
                            setCharacterAttributes(wordL, wordR - wordL, attblue, false);
                        } else if (text.substring(wordL, wordR).matches("(\\W)*(INT|DEC|CAD|\"|')")) {
                            setCharacterAttributes(wordL, wordR - wordL, attgreen, false);
                        } else if (text.substring(wordL, wordR).matches("(\\W)*(RET|ETD|SLD)")) {
                            setCharacterAttributes(wordL, wordR - wordL, attred, false);
                        } else {
                            setCharacterAttributes(wordL, wordR - wordL, attblack, false);
                        }
                        wordL = wordR;

                    }
                    wordR++;
                }
            }

            public void romeve(int offs, int len) throws BadLocationException {
                super.remove(offs, len);

                String text = getText(0, getLength());
                int before = findLastNonWordChar(text, offs);
                if (before < 0) {
                    before = 0;
                }
            } 
        }; 
        JTextPane txt = new JTextPane(doc);
        String temp = jtpCode.getText();
        jtpCode.setStyledDocument(txt.getStyledDocument());
        jtpCode.setText(temp);        
        
    
    }
    
    private void inizializar(){
        //importante
        dir= new Directorio();
        
        setTitle("#CodeIDERyJ");
        String[] options = new String[]{"Guardar y continuar","Descargar"};
        
        numerolinea = new NumeroLinea(jtpCode);
        
        jScrollPane1.setRowHeaderView(numerolinea);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCompilar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpCode = new javax.swing.JTextPane();
        btnNuevo = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        btnAbrir1 = new javax.swing.JButton();
        btnReservadas1 = new javax.swing.JButton();
        btnIdentificador = new javax.swing.JButton();
        btnTokens = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaCompile = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCompilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/Icon/icons8_code_48px.png"))); // NOI18N
        btnCompilar.setText("Reservadas");
        btnCompilar.setToolTipText("Abrir documento");
        btnCompilar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompilar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/pressed/icons8_code_48px_p.png"))); // NOI18N
        btnCompilar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/On Layer/icons8_code_48px_on.png"))); // NOI18N
        btnCompilar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompilarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, 70));

        jtpCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtpCodeKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtpCode);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 1180, 360));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/Icon/icons8_code_file_48px.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("Archivo Nuevo");
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/pressed/icons8_code_file_48px_p.png"))); // NOI18N
        btnNuevo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/On Layer/icons8_code_file_48px_on.png"))); // NOI18N
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 70));

        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/Icon/icons8_save_48px.png"))); // NOI18N
        btnGuardar1.setText("Guardar");
        btnGuardar1.setToolTipText("Guardar documento");
        btnGuardar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/pressed/icons8_save_48px_p.png"))); // NOI18N
        btnGuardar1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/On Layer/icons8_save_48px_on.png"))); // NOI18N
        btnGuardar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 70));

        btnAbrir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/Icon/icons8_opened_folder_48px.png"))); // NOI18N
        btnAbrir1.setText("Abrir");
        btnAbrir1.setToolTipText("Abrir documento");
        btnAbrir1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/pressed/icons8_opened_folder_48px_P.png"))); // NOI18N
        btnAbrir1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/On Layer/icons8_opened_folder_48px_ON.png"))); // NOI18N
        btnAbrir1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbrir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, 70));

        btnReservadas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/Icon/icons8-text-color-48.png"))); // NOI18N
        btnReservadas1.setText("Reservadas");
        btnReservadas1.setToolTipText("Abrir documento");
        btnReservadas1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReservadas1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/pressed/icons8-text-color-48.png"))); // NOI18N
        btnReservadas1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/On Layer/icons8-text-color-48.png"))); // NOI18N
        btnReservadas1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReservadas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservadas1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservadas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, 70));

        btnIdentificador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/Icon/icons8-text-cursor-48.png"))); // NOI18N
        btnIdentificador.setText("Identificador");
        btnIdentificador.setToolTipText("Abrir documento");
        btnIdentificador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIdentificador.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/pressed/icons8-text-cursor-48.png"))); // NOI18N
        btnIdentificador.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/On Layer/icons8-text-cursor-48.png"))); // NOI18N
        btnIdentificador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdentificadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnIdentificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, 70));

        btnTokens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/Icon/icons8-index-48.png"))); // NOI18N
        btnTokens.setText("Tokens");
        btnTokens.setToolTipText("Abrir documento");
        btnTokens.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTokens.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/pressed/icons8-index-48.png"))); // NOI18N
        btnTokens.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/codeideryj/iconos/On Layer/icons8-index-48.png"))); // NOI18N
        btnTokens.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTokensActionPerformed(evt);
            }
        });
        getContentPane().add(btnTokens, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, 70));

        jtaCompile.setColumns(20);
        jtaCompile.setRows(5);
        jScrollPane2.setViewportView(jtaCompile);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 1180, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCompilarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        jtaCompile.setText("");
        dir.Nuevo(this);
        clearAllComp();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        // TODO add your handling code here:
        dir.Guardar(this);
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnAbrir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrir1ActionPerformed
        // TODO add your handling code here:
        dir.Abrir(this);

    }//GEN-LAST:event_btnAbrir1ActionPerformed

    private void btnReservadas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservadas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservadas1ActionPerformed

    private void btnIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIdentificadorActionPerformed

    private void btnTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTokensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTokensActionPerformed

    private void jtpCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpCodeKeyReleased
        // TODO add your handling code here:
        int keyCode=evt.getKeyCode();
        if ((keyCode >= 65 && keyCode <= 90) || (keyCode >= 48 && keyCode <= 57)
                || (keyCode >= 97 && keyCode <= 122) || (keyCode != 27 && !(keyCode >= 37
                && keyCode <= 40) && !(keyCode >= 16
                && keyCode <= 18) && keyCode != 524
                && keyCode != 20)) {
            if (!getTitle().contains("*")){
                setTitle(getTitle() + "*");
                
            }
    }
    }//GEN-LAST:event_jtpCodeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDE().setVisible(true);
            }
        });
    }

    public void clearAllComp(){
        jtaCompile.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir1;
    private javax.swing.JButton btnCompilar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnIdentificador;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReservadas1;
    private javax.swing.JButton btnTokens;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea jtaCompile;
    public javax.swing.JTextPane jtpCode;
    // End of variables declaration//GEN-END:variables
}
