#!/bin/bash
# Author: José Rodolfo (jric2002)
declare -r RESET="\e[0m"
declare -r BOLD="\e[1m"
declare -r DIM="\e[2m"
declare -r ITALIC="\e[3m"
declare -r UNDERLINE="\e[4m"
declare -r BLINK="\e[5m"
declare -r REVERSE="\e[7m"
declare -r HIDDEN="\e[8m"
declare -r STRIKETHROUGH="\e[9m"

declare -r BLACK="\e[30m"
declare -r RED="\e[31m"
declare -r GREEN="\e[32m"
declare -r YELLOW="\e[33m"
declare -r BLUE="\e[34m"
declare -r PURPLE="\e[35m"
declare -r CYAN="\e[36m"
declare -r LIGHT_GRAY="\e[37m"

declare -r LIGHT_BLACK="\e[1;30m"
declare -r LIGHT_RED="\e[1;31m"
declare -r LIGHT_GREEN="\e[1;32m"
declare -r LIGHT_YELLOW="\e[1;33m"
declare -r LIGHT_BLUE="\e[1;34m"
declare -r LIGHT_PURPLE="\e[1;35m"
declare -r LIGHT_CYAN="\e[1;36m"
declare -r GRAY="\e[1;37m"

declare -r BLACK_BG="\e[40m"
declare -r RED_BG="\e[41m"
declare -r GREEN_BG="\e[42m"
declare -r YELLOW_BG="\e[43m"
declare -r BLUE_BG="\e[44m"
declare -r PURPLE_BG="\e[45m"
declare -r CYAN_BG="\e[46m"
declare -r LIGHT_GRAY_BG="\e[47m"